services:
  app:
    build:
      args:
        user: clib
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: viacep
    container_name: viacep-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - viacep
  
  db:
    image: mysql:8.0
    container_name: viacep-db
    restart: unles-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

networks:
  viacep:
    driver: bridge